// frontend/components/ViewTracker.tsx
'use client';

import { useEffect, useRef } from 'react';
import { incrementViews } from '@/lib/api';

interface ViewTrackerProps {
  postId: number;
}

export default function ViewTracker({ postId }: ViewTrackerProps) {
  const hasTracked = useRef(false);

  useEffect(() => {
    if (hasTracked.current) return;
    hasTracked.current = true;

    // Increment view count on client side
    incrementViews(postId).catch(console.error);
  }, [postId]);

  return null;
}

// frontend/aura/components/ViewTracker.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { usePostView } from "~~/composables/useApi";

interface Props {
	postId: number;
}

const props = defineProps<Props>();

const hasTracked = ref(false);

onMounted(() => {
	if (hasTracked.value) return;
	hasTracked.value = true;

	// Increment view count on client side
	usePostView(props.postId).catch(console.error);
});
</script>

<!-- This component renders nothing — it just tracks views -->
<template>
  <div v-show="false" />
</template>
