// frontend/aura/components/Skeleton.vue
<script setup lang="ts">
defineProps<{
	/** Skeleton type to render */
	type: "post-list" | "post-detail" | "sidebar" | "page";
}>();
</script>

<template>
  <!-- Post list skeleton -->
  <div v-if="type === 'post-list'" class="space-y-8">
    <div v-for="i in 5" :key="i" class="bg-white dark:bg-gray-900 rounded-lg shadow-sm p-6">
      <div class="animate-pulse space-y-4">
        <div class="h-6 bg-gray-200 dark:bg-gray-700 rounded w-3/4" />
        <div class="flex items-center gap-4">
          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-20" />
          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-16" />
        </div>
        <div class="space-y-2">
          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded" />
          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-5/6" />
        </div>
        <div class="flex gap-2">
          <div class="h-6 bg-gray-200 dark:bg-gray-700 rounded w-16" />
          <div class="h-6 bg-gray-200 dark:bg-gray-700 rounded w-20" />
        </div>
      </div>
    </div>
  </div>

  <!-- Post detail skeleton -->
  <article v-else-if="type === 'post-detail'" class="max-w-3xl mx-auto">
    <div class="animate-pulse space-y-6">
      <div class="space-y-4">
        <div class="h-10 bg-gray-200 dark:bg-gray-700 rounded w-full" />
        <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2" />
      </div>
      <div class="h-64 bg-gray-200 dark:bg-gray-700 rounded-lg" />
      <div class="space-y-3">
        <div
          v-for="i in 8" :key="i" class="h-4 bg-gray-200 dark:bg-gray-700 rounded"
          :style="{ width: `${70 + Math.random() * 30}%` }"
        />
      </div>
    </div>
  </article>

  <!-- Sidebar skeleton -->
  <aside v-else-if="type === 'sidebar'" class="space-y-8">
    <div class="bg-white dark:bg-gray-900 rounded-lg p-4">
      <div class="h-5 bg-gray-200 dark:bg-gray-700 rounded w-20 mb-4" />
      <div class="animate-pulse space-y-2">
        <div v-for="i in 4" :key="i" class="h-4 bg-gray-200 dark:bg-gray-700 rounded" />
      </div>
    </div>
    <div class="bg-white dark:bg-gray-900 rounded-lg p-4">
      <div class="h-5 bg-gray-200 dark:bg-gray-700 rounded w-16 mb-4" />
      <div class="flex flex-wrap gap-2 animate-pulse">
        <div v-for="i in 8" :key="i" class="h-6 bg-gray-200 dark:bg-gray-700 rounded-full w-16" />
      </div>
    </div>
    <div class="bg-white dark:bg-gray-900 rounded-lg p-4">
      <div class="h-5 bg-gray-200 dark:bg-gray-700 rounded w-24 mb-4" />
      <div class="animate-pulse space-y-3">
        <div v-for="i in 3" :key="i" class="space-y-1">
          <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full" />
          <div class="h-3 bg-gray-200 dark:bg-gray-700 rounded w-1/3" />
        </div>
      </div>
    </div>
  </aside>

  <!-- Full page skeleton -->
  <div v-else class="flex flex-col lg:flex-row gap-8">
    <div class="flex-1">
      <Skeleton type="post-list" />
    </div>
    <div class="w-full lg:w-64 shrink-0">
      <Skeleton type="sidebar" />
    </div>
  </div>
</template>

// frontend/components/Skeleton.tsx
// Post list skeleton loader
export function PostListSkeleton() {
  return (
    <div className="space-y-8">
      {Array.from({ length: 5 }).map((_, i) => (
        <div key={i} className="bg-white dark:bg-gray-900 rounded-lg shadow-sm p-6">
          <div className="animate-pulse space-y-4">
            {/* Title */}
            <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-3/4" />
            {/* Meta */}
            <div className="flex items-center gap-4">
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-20" />
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-16" />
            </div>
            {/* Excerpt */}
            <div className="space-y-2">
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded" />
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-5/6" />
            </div>
            {/* Tags */}
            <div className="flex gap-2">
              <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-16" />
              <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-20" />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// Post detail skeleton
export function PostDetailSkeleton() {
  return (
    <article className="max-w-3xl mx-auto">
      <div className="animate-pulse space-y-6">
        {/* Header */}
        <div className="space-y-4">
          <div className="h-10 bg-gray-200 dark:bg-gray-700 rounded w-full" />
          <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2" />
        </div>
        {/* Cover */}
        <div className="h-64 bg-gray-200 dark:bg-gray-700 rounded-lg" />
        {/* Content */}
        <div className="space-y-3">
          {Array.from({ length: 8 }).map((_, i) => (
            <div
              key={i}
              className="h-4 bg-gray-200 dark:bg-gray-700 rounded"
              style={{ width: `${Math.random() * 30 + 70}%` }}
            />
          ))}
        </div>
      </div>
    </article>
  );
}

// Sidebar skeleton
export function SidebarSkeleton() {
  return (
    <aside className="space-y-8">
      {/* Categories */}
      <div className="bg-white dark:bg-gray-900 rounded-lg p-4">
        <div className="h-5 bg-gray-200 dark:bg-gray-700 rounded w-20 mb-4" />
        <div className="animate-pulse space-y-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-4 bg-gray-200 dark:bg-gray-700 rounded" />
          ))}
        </div>
      </div>
      {/* Tags */}
      <div className="bg-white dark:bg-gray-900 rounded-lg p-4">
        <div className="h-5 bg-gray-200 dark:bg-gray-700 rounded w-16 mb-4" />
        <div className="flex flex-wrap gap-2 animate-pulse">
          {Array.from({ length: 8 }).map((_, i) => (
            <div key={i} className="h-6 bg-gray-200 dark:bg-gray-700 rounded-full w-16" />
          ))}
        </div>
      </div>
      {/* Popular posts */}
      <div className="bg-white dark:bg-gray-900 rounded-lg p-4">
        <div className="h-5 bg-gray-200 dark:bg-gray-700 rounded w-24 mb-4" />
        <div className="animate-pulse space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="space-y-1">
              <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full" />
              <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded w-1/3" />
            </div>
          ))}
        </div>
      </div>
    </aside>
  );
}

// Full page skeleton
export function PageSkeleton() {
  return (
    <div className="flex flex-col lg:flex-row gap-8">
      <div className="flex-1">
        <PostListSkeleton />
      </div>
      <div className="w-full lg:w-64 shrink-0">
        <SidebarSkeleton />
      </div>
    </div>
  );
}
