// frontend/nuxt/app/pages/posts/[slug].vue
<script setup lang="ts">
import { usePost } from '../../../composables/useApi';

const route = useRoute();
const { data: post, pending, error } = await usePost(route.params.slug as string);
</script>

<template>
  <div class="max-w-3xl mx-auto">
    <!-- Back link -->
    <NuxtLink
      to="/"
      class="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-blue-600 transition-colors mb-6"
    >
      <Icon icon="lucide:arrow-left" class="w-4 h-4" />
      返回首页
    </NuxtLink>

    <!-- Loading state -->
    <div v-if="pending" class="space-y-4">
      <div class="bg-gray-100 animate-pulse h-8 rounded-lg w-3/4"></div>
      <div class="bg-gray-100 animate-pulse h-64 rounded-lg"></div>
      <div class="bg-gray-100 animate-pulse h-4 rounded-lg"></div>
      <div class="bg-gray-100 animate-pulse h-4 rounded-lg"></div>
      <div class="bg-gray-100 animate-pulse h-4 rounded-lg w-5/6"></div>
    </div>

    <!-- Error state -->
    <div
      v-else-if="error"
      class="text-center py-12 text-gray-500"
    >
      加载失败: {{ error.message }}
    </div>

    <!-- Post not found -->
    <div
      v-else-if="!post"
      class="text-center py-12 text-gray-500"
    >
      文章不存在
    </div>

    <!-- Post content -->
    <article v-else class="prose prose-lg max-w-none">
      <header class="mb-8">
        <h1 class="text-3xl sm:text-4xl font-bold text-gray-900 mb-6 leading-tight">
          {{ post.title }}
        </h1>

        <div class="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-gray-600 mb-6">
          <span v-if="post.category" class="flex items-center gap-2">
            <Icon icon="lucide:folder" class="w-4 h-4" />
            {{ post.category.name }}
          </span>
          <span class="flex items-center gap-2">
            <Icon icon="lucide:calendar" class="w-4 h-4" />
            {{ new Date(post.created_at).toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' }) }}
          </span>
          <span class="flex items-center gap-2">
            <Icon icon="lucide:eye" class="w-4 h-4" />
            {{ post.views }} 次阅读
          </span>
        </div>

        <div
          v-if="post.excerpt"
          class="text-xl text-gray-600 leading-relaxed mb-6"
        >
          {{ post.excerpt }}
        </div>
      </header>

      <!-- Markdown content -->
      <div
        v-if="post.content"
        class="mt-8 text-gray-800 leading-relaxed"
        v-html="post.content"
      ></div>

      <!-- Tags -->
      <footer v-if="post.tags && post.tags.length" class="mt-12 pt-8 border-t border-gray-200">
        <div class="flex flex-wrap gap-2">
          <span
            v-for="tag in post.tags"
            :key="tag.id"
            class="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gray-100 text-gray-700 rounded-full text-sm"
          >
            <Icon icon="lucide:tag" class="w-3.5 h-3.5" />
            {{ tag.name }}
          </span>
        </div>
      </footer>
    </article>
  </div>
</template>

<route lang="json">
{
  "meta": {
    "title": "文章详情",
    "description": "X-Blog - 技术博客文章详情"
  }
}
</route>

// frontend/app/posts/[slug]/page.tsx
import { fetchPost } from '@/lib/api';
import Markdown from '@/components/Markdown';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Tag } from '@/types';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import ViewTracker from '@/components/ViewTracker';
import { Calendar, Folder, Tag as TagIcon, Eye, ArrowLeft, Share2, Clock } from 'lucide-react';

const CommentList = dynamic(() => import('@/components/CommentList'), {
  loading: () => <div className="animate-pulse h-32 bg-gray-50 rounded-xl" />,
});

const CommentForm = dynamic(() => import('@/components/CommentForm'), {
  loading: () => <div className="animate-pulse h-24 bg-gray-50 rounded-xl" />,
});

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  let post;
  try {
    post = await fetchPost(slug);
  } catch {
    return {};
  }

  return {
    title: post.title,
    description: post.excerpt || post.content.slice(0, 150),
    openGraph: {
      title: post.title,
      description: post.excerpt || post.content.slice(0, 150),
      type: 'article',
      publishedTime: post.created_at,
      authors: ['X-Blog'],
      tags: post.tags.map((t: Tag) => t.name),
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.excerpt || post.content.slice(0, 150),
    },
  };
}

export default async function PostPage({ params }: PageProps) {
  const { slug } = await params;

  let post;
  try {
    post = await fetchPost(slug);
  } catch {
    notFound();
  }

  const date = new Date(post.created_at).toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const readTime = Math.max(1, Math.ceil(post.content.length / 500));

  return (
    <>
      <ViewTracker postId={post.id} />
      
      <article className="max-w-3xl mx-auto">
        {/* 返回按钮 */}
        <Link 
          href="/" 
          className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-blue-600 transition-colors mb-6"
        >
          <ArrowLeft className="w-4 h-4" />
          返回首页
        </Link>

        {/* 文章头部 */}
        <header className="mb-8">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4 leading-tight">
            {post.title}
          </h1>
          
          {/* 元信息 */}
          <div className="flex flex-wrap items-center gap-4 text-sm text-gray-500">
            <span className="flex items-center gap-1.5">
              <Calendar className="w-4 h-4" />
              {date}
            </span>
            <span className="flex items-center gap-1.5">
              <Clock className="w-4 h-4" />
              {readTime} 分钟阅读
            </span>
            <span className="flex items-center gap-1.5">
              <Eye className="w-4 h-4" />
              {post.views || 0} 次阅读
            </span>
          </div>

          {/* 分类和标签 */}
          <div className="flex flex-wrap items-center gap-3 mt-4">
            {post.category && (
              <Link
                href={`/?category_id=${post.category.id}`}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gradient-to-r from-purple-50 to-indigo-50 text-purple-700 rounded-full text-sm font-medium hover:from-purple-100 hover:to-indigo-100 transition-colors"
              >
                <Folder className="w-3.5 h-3.5" />
                {post.category.name}
              </Link>
            )}
            {post.tags.map((tag: Tag) => (
              <Link
                key={tag.id}
                href={`/?tag_id=${tag.id}`}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 rounded-full text-sm font-medium hover:from-blue-100 hover:to-indigo-100 transition-colors"
              >
                <TagIcon className="w-3.5 h-3.5" />
                #{tag.name}
              </Link>
            ))}
          </div>
        </header>

        {/* 分割线 */}
        <div className="h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent mb-8" />

        {/* 文章内容 */}
        <div className="prose prose-lg max-w-none mb-12">
          <Markdown content={post.content} />
        </div>

        {/* 分割线 */}
        <div className="h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent mb-8" />

        {/* 评论区 */}
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <Share2 className="w-5 h-5 text-blue-600" />
            评论
          </h2>
          <CommentList postId={post.id} />
          <div className="mt-6">
            <CommentForm postId={post.id} />
          </div>
        </section>

        {/* SEO Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'BlogPosting',
              headline: post.title,
              description: post.excerpt || post.content.slice(0, 150),
              datePublished: post.created_at,
              author: {
                '@type': 'Person',
                name: 'X-Blog',
              },
            }),
          }}
        />
      </article>
    </>
  );
}
