// frontend/app/admin/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { adminLogin } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { Lock, User, LogIn, AlertCircle } from 'lucide-react';
import Link from 'next/link';

export default function LoginPage() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const { login } = useAuth();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const result = await adminLogin(username, password);
      login(result.access_token);
      router.push('/admin');
    } catch {
      setError('用户名或密码错误，请重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-50 via-white to-blue-50 p-4">
      {/* 背景装饰 */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-blue-100 rounded-full blur-3xl opacity-50" />
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-indigo-100 rounded-full blur-3xl opacity-50" />
      </div>

      <Card className="w-full max-w-md relative shadow-xl border-0">
        <CardHeader className="text-center pb-2">
          <div className="mx-auto w-14 h-14 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-2xl flex items-center justify-center mb-4 shadow-lg shadow-blue-600/20">
            <LogIn className="w-7 h-7 text-white" />
          </div>
          <CardTitle className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
            X-Blog 管理
          </CardTitle>
          <CardDescription className="text-gray-500">
            输入您的账号信息登录管理后台
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-4">
          <form onSubmit={handleSubmit} className="space-y-5">
            {error && (
              <div className="flex items-center gap-2 p-3 text-sm text-red-600 bg-red-50 rounded-lg border border-red-100">
                <AlertCircle className="w-4 h-4 shrink-0" />
                {error}
              </div>
            )}
            
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">用户名</label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <Input
                  placeholder="请输入用户名"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="pl-10 h-11"
                  required
                />
              </div>
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">密码</label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请输入密码"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="pl-10 h-11"
                  required
                />
              </div>
            </div>
            
            <Button 
              type="submit" 
              className="w-full h-11 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 shadow-lg shadow-blue-600/20"
              disabled={loading}
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  登录中...
                </span>
              ) : (
                <span className="flex items-center gap-2">
                  <LogIn className="w-4 h-4" />
                  登录
                </span>
              )}
            </Button>
          </form>
          
          <div className="mt-6 pt-6 border-t text-center">
            <Link 
              href="/" 
              className="text-sm text-gray-500 hover:text-blue-600 transition-colors"
            >
              ← 返回博客首页
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// frontend/aura/app/pages/admin/login.vue
<!--
  Admin Login Page
  Migrated from Next.js /app/admin/login/page.tsx to Nuxt 4 / Vue 3.
  Uses useAdminAuth composable for token storage + navigation.
-->
<script setup lang="ts">
import { ref } from 'vue';
import { useAdminAuth, adminLoginRequest } from '~/composables/useAdminAuth';

const { login } = useAdminAuth();
const username = ref('');
const password = ref('');
const error = ref<string | null>(null);
const isPending = ref(false);

async function handleLogin() {
  if (!username.value || !password.value) return;

  error.value = null;
  isPending.value = true;

  try {
    const { data, error: fetchError } = await adminLoginRequest(
      username.value,
      password.value
    );

    if (fetchError.value) {
      error.value = '登录失败：用户名或密码错误';
      return;
    }

    if (data.value?.access_token) {
      login(data.value.access_token);
      navigateTo('/admin/posts', { replace: true });
    } else {
      error.value = '登录失败：未收到访问令牌';
    }
  } catch (e) {
    error.value = '登录失败：网络错误';
  } finally {
    isPending.value = false;
  }
}
</script>

<template>
  <div class="w-full max-w-md">
    <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-xl border border-gray-100 dark:border-gray-700 p-8">
      <div class="text-center mb-8">
        <div
          class="w-16 h-16 rounded-full bg-gradient-to-r from-blue-500 to-indigo-500 flex items-center justify-center mx-auto mb-4"
        >
          <Icon icon="lucide:lock" class="w-8 h-8 text-white" />
        </div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">
          管理员登录
        </h1>
        <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">
          请输入管理员账号密码
        </p>
      </div>

      <form @submit.prevent="handleLogin" class="space-y-5">
        <div>
          <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
          >用户名
          </label>
          <input
            v-model="username"
            type="text"
            placeholder="用户名"
            required
            class="w-full px-4 py-3 border border-gray-200 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
          >
        </div>

        <div>
          <label
            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
          >密码
          </label>
          <input
            v-model="password"
            type="password"
            placeholder="密码"
            required
            class="w-full px-4 py-3 border border-gray-200 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
          >
        </div>

        <div v-if="error" class="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
          <p class="text-sm text-red-600 dark:text-red-400">
            {{ error }}
          </p>
        </div>

        <button
          type="submit"
          :disabled="isPending || !username || !password"
          class="w-full py-3 px-4 bg-gradient-to-r from-blue-500 to-indigo-500 text-white rounded-xl font-medium hover:from-blue-600 hover:to-indigo-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-blue-500/20"
        >
          <span v-if="isPending" class="flex items-center justify-center gap-2">
            <Icon icon="lucide:loader-2" class="w-4 h-4 animate-spin" />
            登录中...
          </span>
          <span v-else>登录</span>
        </button>
      </form>
      <div class="mt-6 pt-6 border-t text-center">
        <NuxtLink
          to="/"
          class="text-sm text-gray-500 hover:text-blue-600 transition-colors"
        >
          ← 返回博客首页
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<!--
  Use the admin layout (no sidebar for login page)
-->
<script lang="ts">
export default {
  layout: 'admin',
  auth: false,
};
</script>
